.gitmodules, README.md, src/Ethereum/TokensPriceFeeds.sol, src/L2/ChatterPay.sol, test/ChatterPay_Native_Test.t.sol
- [docs] 📝 update documentation
- [chore] 🐛 add spdx and pragma to avoid forge test warning
- [fix] 🐛 fix case in forge/console contract name
- [docs] 📝 include api3, scroll and oz in documentation
- [feat] 📦 add api3 module
- [feat] ✨ add tokens price feeds contract
- [refactor] ♻️ refactor api3 contract
=> merge feature/20240803 into main

src/L2/ChatterPayNFT.sol
- [feature] :poop: write bad code that needs to be improved (workaround)
=> merge feature/workaround-mint-icp into develop

src/L2/ChatterPayNFT.sol
=> [feat] :sparkles: add uri parameter in mint-copy (#22)

README.md
- [fix] :docs: fix technical-overview link (#27)
=> mrege feature/contracts-docs into develop

.doc/content.md
- [docs] :memo: fix docs references
=> merge fix/docs into develop

README.md
- [docs] :memo: update general documentation
=> merge feature/readme into develop

foundry.toml, script/DeployAllContracts.s.sol, script/DeployAllContracts.v2.s.sol, script/DeployChatterPay.s.sol, script/DeployFactory.s.sol, script/DeployNFTs.s.sol, script/DeployPaymaster.s.sol, script/DeployVault.s.sol, script/HelperConfig.s.sol, src/L2/ChatterPay.sol, src/L2/ChatterPayPaymaster.sol, src/L2/ChatterPayWalletFactory.sol, test/ChatterPayTest.t.sol
=> [feat] added new and fixed deploy scripts & tests

.github/workflows/test.yml
- [ci] ♻️ set up cache for fountry en gihub tests
=> [ci] :recycle: set up cache for fountry en gihub tests

README.md
- [fix] :memo: remove extra quotes in readme and add additional info
=> merge fix/readme-markdown into develop

.doc/technical-overview/contracts-details.md, .doc/technical-overview/overview.md
- [docs] :memo: update contracts technical-overview
=> merge feature/contracts-documentation into develop

script/DeployAllContracts.s.sol
- [fix] 🐛 add try-catch when deployed_paymaster_address is empty in env
- [chore] 🔊 remove simpleSwapAddress from console.log in deployAllContracts 
- [chore] 🔊 add swapRouter in console.log in deployAllContracts
=> merge fix/deploy-all-contracts into develop

.doc/deployment/deployment-guidelines.md, script/utils/HelperConfig.s.sol
- [feat] ✨ add arbiturm one (mainnet) config 
- [chore] 💡 update comments in HelperConfig.s.sol 
- [docs] 📝 add contracts deployments links in doc
=> merge feature/add-mainnet-config into develop

src/ChatterPay.sol, test/setup/BaseTest.sol
- [revert] ⏪ uncomment _disableInitializers in chatterpay.sol
- [fix] 🐛 remove direct initialization in baseTest due to _disableInitialization
=> merge fix/chatterpay-tests into develop

README.md
- [docs] :memo: fix auditors links in readme
=> merge feature/readme-2 into develop (2)

.doc/deployment/deployment-guidelines.md
- [docs] :memo: fix contracts deployment documentation
=> merge fix/doc-contracts-addresses into develop

.doc/deployment/deployment-guidelines.md, example_env
- [docs] 📝 add chainlink documentation
- [docs] 📝 add scroll documentation
=> merge fix/docs-chainlink into develop

src/ChatterPayPaymaster.sol
- Switched to using OpenZeppelin's ECDSA.recover for signature verification in _recoverSigner.
This improves security by rejecting malleable signatures and simplifies the code by removing manual parsing of r, s, v.
- [refactor] ♻️ replace manual ecrecover with OpenZeppelin ECDSA recover
- #99
=> merge feature/99-ecdsa into develop

src/ChatterPayNFT.sol, test/modules/NftModule.t.sol
- Added basic URI validation to prevent metadata injection vulnerabilities, and included tests for the ChatterPayNFT contract covering minting flows and error handling.
- [feat] 🔒 add basic URI sanitization to prevent metadata injection 
- [test] 🧪 add tests for ChatterPayNFT minting logic 
- #98
=> merge feature/sanitize-nft-metadata into develop

src/ChatterPay.sol, test/modules/AdminModule.t.sol
- Improved the upgradability and maintainability of the `ChatterPay` contract by refactoring its internal state into a structured layout. 
- Added a dedicated test to verify that the contract state remained consistent after an upgrade. 
- Removed the unused `__gap` slot.
[refactor] 🔥 remove unused _-gap storage slot in chatterpay (#39)
[refactor] ♻️ refactor chatteray state struct and storage access (#93)
[test] 🧪 add test to verify state is preserved after upgrade (#93)
- #39
- #93
=> merge feature/93 into feature/20250420

script/utils/HelperConfig.s.sol
- Added Mainnet config (Arbitrum One and Scroll) in HelperConfig.
=> merge feature/20250428 into develop

script/uniswap_check_liquidity.sh, script/utils/HelperConfig.s.sol
- [chore] :hammer: adjust uniswap check liquidity script
=> merge feature/adjust-uniswap-script into develop

script/utils/HelperConfig.s.sol
- Updated whitelisted token addresses with their corresponding price feeds. 
- Updated Uniswap deployments in Scroll mainnet
=> merge feat/scr-mainnet-addresses into develop

script/utils/HelperConfig.s.sol, src/ChatterPay.sol
- This PR reduces the default fee applied to token operations from 50 cents to 20 cents. The change aims to make transactions more affordable for users while maintaining sustainability for the protocol. This update is part of ongoing efforts to optimize cost-efficiency and enhance the user experience. 
- #157
=> merge feature/157-default-fee into develop

.doc/deployment/deployment-guidelines.md
- [docs] :memo: add uniswap scroll documentation
=> merge feature/doc-uniswap into develop

test/modules/AdminModule.t.sol, test/modules/SwapModule.t.sol, test/modules/TransferModule.t.sol
- [fix] :bug: update fee in cents for tests (#157)
=> merge fix/test-default-fee in develop

.github/FUNDING.yml
=> merge feature/funding to develop
